#!/bin/bash
# Copyright (c) 2022-2023, AllWorldIT.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.


# Load our configuration
set -a
. /etc/celery/celery.conf
set +a


export PATH=/app/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin


# Next thing we do is check if we're bootstraping this node
ARGS=()

# Work out the command to execute and parameters based on the Celery instance type
if [ "$CELERY_INSTANCE_TYPE" = "worker" ]; then
    ARGS+=("worker")
    ARGS+=("--hostname=worker@%h")
elif [ "$CELERY_INSTANCE_TYPE" = "beat" ]; then
    ARGS+=("beat")
    ARGS+=("--schedule=/run/celery/celerybeat-schedule")
fi

# See if we need to set the log level
if [ -n "$CELERY_LOG_LEVEL" ]; then
    ARGS+=("--loglevel=$CELERY_LOG_LEVEL")
fi


# Make sure we're in the correct directory before we start celery
cd /app

exec /app/.venv/bin/celery --app "$CELERY_APP" --workdir /app "${ARGS[@]}"
